### ISSUE TITLE
System user tags are not created

### ISSUE THREAD

**Issue by krystan** [cloudposse/terraform-aws-iam-system-user#22]
## Describe the Bug
When creating a simple system user, although the tags are set using var.tags in the tags attribute the IAM user does not have tags applied.

However if you hard code tags these are applied

## Expected Behavior
An IAM user should be created with tags as contained in the map that is passed to the module.

## Steps to Reproduce
Steps to reproduce the behaviour:

The following code when run in a plan, demonstrates this issue perfectly:

```
provider "aws" {
  region  = "eu-west-1"
  version = "~> 2.53"
}

terraform {
  backend "s3" {}
}

module "s3_user" {
  source        = "git::https://github.com/cloudposse/terraform-aws-iam-system-user.git?ref=tags/0.7.0"
  namespace     = "test-me-posse"
  stage         = "test"
  environment   = "dev"
  name          = "com.krystanhonour-blobbybo"
  attributes    = []
  tags          = {
      Terraform = "true"
      Test = "True"
  }
  enabled       = true
  force_destroy = false
  path          = "/"
}

module "label" {
  source      = "git::https://github.com/cloudposse/terraform-null-label.git?ref=tags/0.16.0"
  namespace   = "bob"
  stage       = "test"
  environment = "Dev"
  name        = "myLabel"
  attributes  = []
  delimiter   = ""
  tags        = { Test = "true"}
  enabled     = true
}

resource "aws_iam_user" "default" {
  count         = 1
  name          = "my-test-user"
  path          = "/"
  force_destroy = false
  tags          = module.label.tags
}
```

## Environment (please complete the following information):
Linux Ubuntu 20.x
Terraform v0.12.26
Terragrunt v0.23.27

Tested In WSL, Linux and Windows confirmed an issue on all.

## Additional Context
This has been reported as a bug in the s3 bucket module when a user is created there it ultimately relies on this module and passes tags down, whilst the bug is not with that module there is a bug report there: https://github.com/cloudposse/terraform-aws-s3-bucket/issues/7

**Comment by nitrocode** [comment]
If you use version `0.9.0` then it will use tags for the user.

See the [releases](https://github.com/cloudposse/terraform-aws-iam-system-user/releases) page.
