### ISSUE TITLE
invalid value for name aws_iam_user

### ISSUE THREAD

**Issue by finchr** [cloudposse/terraform-aws-iam-system-user#66]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
terraform plan exits with the message "Error: invalid value for name (must only contain alphanumeric characters, hyphens, underscores, commas, periods, @ symbols, plus and equals signs)". I first encountered this error calling `cloudposse/ses/aws` using terragrunt but I can reproduce the error from examples/complete.

## Expected Behavior
I expect the iam user to be created.

## Steps to Reproduce
1. Go to 'examples/complete'
2. Run `terraform init; terraform plan`
5. Enter '.us-east-1'
6. See attached screenshot.

## Screenshots
See attached screenshot.

<img width="1080" alt="Screen Shot 2022-07-08 at 4 14 43 PM" src="https://user-images.githubusercontent.com/2848364/178080977-102c827a-98e8-41bb-9504-0ea4244a4e1a.png">

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: Linux and Mac OS X
 - Version Terraform v1.1.9

**Comment by Nuru** [comment]
This module requires that you provide a name for the IAM user via any or all of the following [terraform-null-label](https://github.com/cloudposse/terraform-null-label/) inputs.

- name
- namespace
- tenant
- environment
- stage
- attributes

Sorry if that was not clear.
